version: '3.8'

services:
  mongo-test:
    container_name: mongo-test
    image: mongo
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27018:27017

  redis-test:
    container_name: redis-test
    image: redis
    command: 'redis-server'
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6380:6379
