version: '3.8'

services:
  submissionbox-backend:
    container_name: backend
    build: ./
    command: npm run dev
    working_dir: /usr/src/submissionbox-backend
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - 3001:3001
    volumes:
      - '/usr/src/app/node_modules'
      - ./:/usr/src/submissionbox-backend

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: USERNAME HERE
      MONGO_INITDB_ROOT_PASSWORD: PASSWORD HERE
    ports:
      - 27017:27017

  redis:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    ports:
      - 6379:6379
